---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
    type: front_end
spec:
 replicas: 3
 selector:
   matchLabels:
     type: front_end
 template:
   metadata:
     name: nginx-pod
     labels:
      type: front_end
   spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 9090
